server:
  port: 8080
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
  liquibase:
    enabled: false
  data:
    elasticsearch:
      cluster-nodes: elasticsearch:9300
      cluster-name: elasticsearch
      repositories:
        enabled: true